### PR TITLE
NLog GoogleStackdriverTarget improve handling of System.Reflection objects

### PR DESCRIPTION
**Pull request by snakefoot**
Protect against System.Reflection Objects like `Assembly`, `MethodInfo`, `Module`, that will dump all types in the the application-assembly.

### CODE REVIEW

**Comment by jskeet** [comment]
Thank you - I'll look at this later on today.

**Comment by jskeet** [comment]
I'll merge this now - I was going to ask for a few more comments and more expression-bodied members, but it's just as easy for me to implement this myself. I'll then create a patch release.

**Comment by snakefoot** [comment]
@jskeet If you are going to make an additional commit, then please add the following property to the BadObject in the unit-test:

```c#
public  class BadObject
{
    public object ExceptionalObject => throw new NotSupportedException();
}
```

This will exercise more of the recovery logic in JsonConverter. And verify it works.

**Comment by jskeet** [comment]
Will do - but I'll probably do that as a separate type with a separate test, just to keep things isolated.

**Comment by jskeet** [comment]
Version 3.0.1 has now been released.

**Comment by snakefoot** [comment]
Wow that was quick. Thank you so much.


---- Jon Skeet wrote ----


Version 3.0.1 has now been released.

**Pull request merged**
