### PR TITLE
Prototype of recording content metadata while downloading

### PR DESCRIPTION
**Pull request by jskeet**
We won't do this until the next major version (as it's a breaking change) but this would address #7897.

This is really just a prototype to:

- Check that it's feasible (looks like it is)
- Provide a straw man of the general design to discuss

### CODE REVIEW

**Comment by lukepuplett** [comment]
Hi Jon, thanks for this. It looks good, and the return type provides an opportunity to expand if ever needed. The expansions that come to mind would be other information that the API/HTTP thinks is useful, e.g. Content-Length, Content-Type, Content-Encoding, Etag, and Last-Modified.

Content-Encoding may be a great or terrible choice. If the downloading of a gzipped blob automatically unzips it, then that information would become useless, incorrect to the programmer. However, if no such decompression occurs then the programmer will need this in order to deal with the stream appropriately.

Etag may also be useless if it's not possible to subsequently use the value in a future conditional request.

The only other thing that came to mind is the property name 'Hash'. Maybe it should be the same as it is in the `Google.Apis.Storage.v1.Data.Object` type, i.e. `Md5Hash` or kept as you have it, which is the same as the source header.

I guess the fear would be if it was `Md5Hash` the JSON API must never switch to another algorithm, or if it did, it'd need to also send the MD5 in another header. As it stands, the JSON API being equivocal on what exactly its "hash" header is, affords the potential to change. This may be extremely unlikely in practice.

I've no experience of maintaining a public C# API and the considerations for breaking changes, so this could be a daft idea, but I wonder if this could be a new method like `DownloadContentAsync` and the other one can be hidden from Intellisense (I don't know what tooling support is like for `EditorBrowsable`) and marked obsolete.

Thanks for your time and sharing early :)

**Comment by lukepuplett** [comment]
I should add that these other HTTP response data may also place too strong a link between the C# API and its underlying transport. I don't know; just thoughts.

**Comment by jskeet** [comment]
Thanks for the comments. It looks like Go already has this: https://pkg.go.dev/cloud.google.com/go/storage#ReaderObjectAttrs

... so we'll align with Go, possibly adding to (or clarifying) what they're returning.

In terms of the hash, this *isn't* the MD5 hash - it's the CRC32 hash, but the value includes the hash type ("crc32=..."). We could potentially make the property return a sequence of hash values, so that if the server ever starts returning multiple values (adding md5 as well as crc32 for example) clients could continue to work. But we'll get to that level of detail when we're closer to being able to merge this.

**Comment by jskeet** [comment]
Closing this PR for now, but leaving the branch. We will almost certainly revive this in March/April as we approach the new major version.

**Pull request closed without merging**
