### PR TITLE
Prototype of moving to ILogger in Spanner

### PR DESCRIPTION
**Pull request by jskeet**
Notes:

The explicit package reference to
Microsoft.Extensions.Logging.Abstractions in Spanner.V1 will be
removed for GAX v4.

Further work to move ExecuteHelper out of the Internal namespace
would be beneficial, and really shouldn't be too hard.

Currently this makes it hard to set a default logger. It's global
state which is convenient but ugly. It wouldn't be too hard to
introduce another place for the default SessionPoolManager's logger
to be set, if we wanted to.

Currently the logging is all based on SessionPoolManager - that's
effectively the root of the logging tree. If we wanted to allow
different SpannerConnections to use different loggers for example,
that might be tricky.

Specifying a SessionPoolManager which creating a new
SpannerConnection is tricky, requiring a
SpannerConnectionStringBuilder... if we decide that it's fine to
require users to create a new SessionPoolManager for custom logging,
we might want to add a convenience overload for SpannerConnection
that accepts a string and a SessionPoolManager.

We now unconditionally log SQL at a Debug level, where previously we
had an option for whether or not to log sensitive information. We
could put that option into SpannerConnection potentially.

This change removes the performance counters we had - but there were
very few of them, and I'd argue that tying them to logging probably
isn't ideal anyway.

There's also one test for commit stats that I haven't rewritten yet
- it would be fairly fiddly to do, but feasible.

### CODE REVIEW

**Comment by jskeet** [comment]
This would address #8201

**Review by amanda-tarafa — COMMENTED** [review]
Yep, this looks good.

I think, that we can add DI extension methods for letting users configure the session pool managar in general and in particular logging. And in that case we can have SpannerConnection  receive a specific logger on the constructor even if they are all using the same session pool manager.
We'll have to write some extra constructors or factory methods that we can make public to expose the configuration functionality to users not using DI or using a different container than MS's?

**Comment by jskeet** [comment]
A few notes as I look over this again...

- We could potentially use an `ILoggerFactory` instead of an `ILogger` in `SessionPoolManager` and `SessionPool`
- Acquiring a session could specify the logger for that session to use as an optional override of the one in the `SessionPool` - that would allow per-connection logging

**Comment by jskeet** [comment]
Closing this as we're somewhat nervous about it - we'd prefer to get more information about how customers use the new `ILogger` support, and do a "better" version of this in the future.

**Pull request closed without merging**
