### PR TITLE
Try a different test style

### PR DESCRIPTION
**Pull request by chrisdunelm**

### CODE REVIEW

**Comment by chrisdunelm** [comment]
Jon, do you think this testing style (in `TopLevelTest.cs`) is an improvement?
It brings the two parts of each test together, but it a little more verbose.

**Comment by chrisdunelm** [comment]
The tests are already in the same file as the namespaces; although in a different root namespace.
I'll put the test-namespaces in the same namespaces as the test, just to make it as simple as possible, then we'll have the namespaces and tests in the same file, with a little verbosity as (easily) possible.

**Comment by jskeet** [comment]
Ah, I'd misread the original diff. It's not as urgent as I'd thought before. Will still try to think about alternative options though...

**Comment by chrisdunelm** [comment]
Please could you LGTM? I can't merge otherwise; and this minor change is a minor improvement ;)

**Pull request merged**
