### PR TITLE
Add Google Cloud Scheduler (no release yet)

### PR DESCRIPTION
**Pull request by jskeet**
We may well want a few snippets or integration tests just to check it works - this is all autogenerated so far.

### CODE REVIEW

**Comment by jskeet** [comment]
Right - will merge as-is, and add some snippets (as a handy form of integration test) in a new PR.

**Comment by jskeet** [comment]
Right - will merge as-is, and add some snippets (as a handy form of integration test) in a new PR.

**Comment by jskeet** [comment]
Hmm. Turns out this only works if the project has an AppEngine app, and that has a location which is supported by Cloud Scheduler. (Mine is in the wrong location...) So I think we'll leave it without any integration tests right now...

**Comment by amanda-tarafa** [comment]
Does that means that the generated Snippets won't pass?

**Comment by jskeet** [comment]
The generated snippets aren't executable tests.

**Comment by amanda-tarafa** [comment]
Ah OK, good to know!

**Pull request merged**
