### PR TITLE
chore: Remove Google.Cloud.BigQuery.DataExchange.Common

### PR DESCRIPTION
**Pull request by jskeet**
This has been removed from the protos, and the beta API no longer
uses it. The package will be delisted.

### CODE REVIEW

**Comment by jskeet** [comment]
The CI failure is expected - we never got round to adjusting the CI scripts to handle API deletion, as it's so rare.

**Comment by jskeet** [comment]
Scratch that - it's complaining about the remaining package. Fixing...

**Comment by jskeet** [comment]
Now fixed - there was a reference to the now-deleted project file in the solution for the beta API.

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Pull request merged**
