### PR TITLE
tools: Move most logic from detect-pr-changes.sh to ReleaseManager

### PR DESCRIPTION
**Pull request by jskeet**
This should make it much easier to tweak, e.g. to handle different TFMs being involved.

### CODE REVIEW

**Comment by jskeet** [comment]
(It looks like our comparison tools don't spot constants - I've raised b/330680714 for that.)

**Comment by jskeet** [comment]
(Obviously I'll remove the second commit before merging.)

**Comment by amanda-tarafa** [comment]
> (It looks like our comparison tools don't spot constants - I've raised b/330680714 for that.)

Nice, I just closed an issue I had created for looking into that.

**Review by amanda-tarafa — APPROVED** [review]
Nice!

**Pull request merged**
