### PR TITLE
Move test dependencies for ASP.NET Core diagnostics into apis.json

### PR DESCRIPTION
**Pull request by jskeet**
This should make #3264 simpler.

cc @henkmollema

### CODE REVIEW

**Comment by henkmollema** [comment]
Thanks! Should the separated dependencies in `Google.Cloud.Diagnostics.AspNetCore.csproj` be added to apis.json as well?

https://github.com/googleapis/google-cloud-dotnet/blob/4bf62d0c32e94798e768111105588a1e9d68ca45/apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.csproj#L34-L40

**Comment by jskeet** [comment]
Hadn't spotted those - yes, will do that now. It'll make it clearer when reviewing apis.json.

(Your PR will need to update those, then run generateprojects.sh to propagate the change.)

**Comment by jskeet** [comment]
Done in a second commit.

**Comment by henkmollema** [comment]
> (Your PR will need to update those, then run generateprojects.sh to propagate the change.)

Do I need to do this if I rebase my branch after this PR is merged?

**Comment by jskeet** [comment]
> Do I need to do this if I rebase my branch after this PR is merged?

Yes, because you're going to want to change some of the version numbers (I'd expect, anyway). Any dependencies which are *just* moved by your current PR should be fine after the rebase, but I'd assumed all these 2.0.x will want to be 2.1.x.

**Comment by henkmollema** [comment]
Ah I see 👍

**Pull request merged**
