### PR TITLE
chore: Detect CRLF files in PRs

### PR DESCRIPTION
**Pull request by jskeet**

### CODE REVIEW

**Comment by jskeet** [comment]
(This is expected to fail on the first commit. Will be fixed in a second.)

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Comment by jskeet** [comment]
Output with just the first commit:

```text
i/crlf  w/crlf  attr/                 	apis/Google.Analytics.Admin.V1Alpha/docs/history.md
i/crlf  w/crlf  attr/                 	apis/Google.Cloud.Domains.V1Beta1/Google.Cloud.Domains.V1Beta1.sln
i/crlf  w/crlf  attr/                 	apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.sln
Error: Process completed with exit code 1.
```

**Review by amanda-tarafa — APPROVED** [review]
LGTM, this is great!

**Pull request merged**
