### PR TITLE
Updates gRPC default version to 2.35.0

### PR DESCRIPTION
**Pull request by amanda-tarafa**
(Releasing will gradually pick up the new version)

### CODE REVIEW

**Review by jskeet — COMMENTED** [review]
Possibly change the generator version we use in toolversions.sh too?
(I suggest making that change and then seeing if anything actually changes - if it does, we'll want to regenerate everything in the same PR to avoid an autosynth avalanche.)

**Comment by amanda-tarafa** [comment]
Ah yes, on both...

**Review by jskeet — APPROVED** [review]
As discussed offline, generation can come later.

**Comment by amanda-tarafa** [comment]
AppVeyor is failing because projects need to be regenerated for non GAs.
I'm looking into fully regenerating though.

**Comment by jskeet** [comment]
Just running generateprojects.sh should be enough - we can get this PR in, then look at generation.

**Comment by amanda-tarafa** [comment]
Ran `generateproject.sh`, only non-GA projects have been updated as expected.
Waiting for green before merging...

**Pull request merged**
