### PR TITLE
Update Retail - change from V2 to V2Beta

### PR DESCRIPTION
**Pull request by jskeet**

### CODE REVIEW

**Comment by jskeet** [comment]
(AppVeyor failure is due to trying to build the now-removed API.)

**Review by chrisdunelm — APPROVED** [review]
LGTM

**Comment by chrisdunelm** [comment]
Just noticed that appveyor is failing with a missing project file.
Is this benign, and caused by the rename?

**Comment by jskeet** [comment]
Yes, precisely that. I thought we'd fix that, but apparently not. Not going to look into it now, given how rarely we remove a directory.

**Pull request merged**
