### PR TITLE
Release Google.Cloud.Tools.SbomGenerator version 0.2.0

### PR DESCRIPTION
**Pull request by amanda-tarafa**

### CODE REVIEW

**Review by jskeet — APPROVED** [review]

**Comment by amanda-tarafa** [comment]
I think this PR is breaking autorelease as the commit has the same (and wrong for this PR) message as a previois PR. I'll submit a new one with the correct commit.

**Comment by jskeet** [comment]
You should be able to just edit the PR title. I *think* that should work.

**Comment by amanda-tarafa** [comment]
Oh, just saw this, trying that first, before merging #11280.

**Comment by amanda-tarafa** [comment]
Changing the PR name didn't work. I'm looking at this in detail internally. I'll flag whatever PR we need to approve/merge if any.

**Comment by amanda-tarafa** [comment]
I think I figured it out, the PR needs to have a non-empty description. Trying now...

**Pull request merged**
