### PR TITLE
chore: update action to trigger conformance tests only for storage PRs

### PR DESCRIPTION
**Pull request by Rishabh-V**

### CODE REVIEW

**Comment by Rishabh-V** [comment]
I will push a dummy commit in storage (and then revert in next commit) to see if it fires for storage.

**Review by jskeet — APPROVED** [review]
I suspect we don't need the `**` at the start, but it won't do any harm.

**Comment by Rishabh-V** [comment]
Conformance tests are being run now. Will revert the whitespace change in next commit.

**Comment by Rishabh-V** [comment]
Triggering conformance tests one more time to test it works with updated path without starting**. (Will revert it in next commit)

**Comment by Rishabh-V** [comment]
> I suspect we don't need the `**` at the start, but it won't do any harm.

Yes Jon. You are correct. Removed starting ** and it is working :)

**Review by amanda-tarafa — APPROVED** [review]

**Pull request merged**
