### PR TITLE
Draft of nested resource references

### PR DESCRIPTION
**Pull request by jskeet**
This is the result of regenerating all APIs with https://github.com/googleapis/gapic-generator-csharp/pull/801

### CODE REVIEW

**Comment by jskeet** [comment]
(Marked as ready for review to hopefully prompt the diff to add a comment...)

**Comment by jskeet** [comment]
The diff *has* run though:
https://github.com/googleapis/google-cloud-dotnet/actions/runs/9096461895/job/25001924433?pr=12963

**Comment by amanda-tarafa** [comment]
Confirming that the added properties to AI Platforms match some of the ones found missing when generating samples with fully expanded messages, as the sample generation code makes the assumption that nested messages have resource references.

**Comment by jskeet** [comment]
Cool - will close this now.

**Pull request closed without merging**
