### PR TITLE
Clarify ServerTimestampAttribute documentation

### PR DESCRIPTION
**Pull request by jskeet**
This is an attempt to make the documentation clearer, as requested in #2830 

cc @codeaid

### CODE REVIEW

**Comment by jskeet** [comment]
(Will wait for feedback from @codeaid before merging)

**Comment by codeaid** [comment]
Overall I'm happy for this to be merged. One thing I would personally change is _"local"_ to _"user-defined"_ (or something similar). I can see how _"local"_ could be confusing as the sentence does not have a specific context. That's just nitpicking though so good to go as is either way.

**Comment by jskeet** [comment]
"Local" is intended to mean "client-side" - i.e. in .NET rather than at the server. Will see if I can clarify that a bit more - I don't think "user-defined" is right necessarily, as the local value could be the one that the server last returned.

**Comment by jskeet** [comment]
Okay, I've made a change - it doesn't sound terribly elegant, but I think it's at least clear.

**Comment by codeaid** [comment]
Looks great! Good to go. Thanks for that!

**Pull request merged**
