### PR TITLE
chore: style fix in datastore project

### PR DESCRIPTION
**Pull request by hemanshv**
Order modifiers async override modifiers in datastore project (style fix).

### CODE REVIEW

**Comment by hemanshv** [comment]
Hi @Rishabh-V ,
Please review this and provide your approval.

**Review by Rishabh-V — APPROVED** [review]
LGTM. Please remove the lex-review label and request review from Jon, Amanda. Thanks.

**Comment by hemanshv** [comment]
Hi @jskeet @amanda-tarafa ,
Please review this and provide your approval.
This has a style fix for datastore project.
Thanks,

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Pull request merged**
