### PR TITLE
chore: generate SBOMs during release

### PR DESCRIPTION
**Pull request by SurferJeffAtGoogle**
How do I test this?

### CODE REVIEW

**Comment by jskeet** [comment]
I'd really like to pause this effort for a bit - I'll need to put some significant time into it, and right now I have other high priority work.

**Comment by jskeet** [comment]
Have been thinking about this overnight - I think I'd like to turn this into a dotnet tool (as we have for a couple of other tools) before we start invoking it. But we don't need to do the refactoring before that. (We do need to work out whether to keep the current "do everything in a directory" or require specific filenames to be passed - I'm personally in favour of the latter.)

@amanda-tarafa Does that sound about right to you? (It'll make it easy to generate SBOMs in other repos, e.g. for Apiary, *and* we don't need to worry about invoking dotnet from the right directory.)

**Comment by amanda-tarafa** [comment]
Yep, doing one file a time matches better with out setup here and in other repos.

**Comment by jskeet** [comment]
Closing this as I'll be sending out a replacement PR once I've released the SBOM generator as a dotnet tool.

**Pull request closed without merging**
