### PR TITLE
Don't run the diff action if the PR has been merged

### LINKED ISSUE #6777: Don't run diff again if a PR label changes after it's already merged

### PR DESCRIPTION
**Pull request by jskeet**
(This wasn't a problem until we started running the action on label
changes.)

Fixes #6777

### CODE REVIEW

**Comment by jskeet** [comment]
(We won't be able to test this easily, and the "merged" field in github.events.pull_request isn't documented as far as I can see, but I *believe* it should work.)

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Comment by jskeet** [comment]
(Testing whether this worked by adding labels now...)

**Comment by jskeet** [comment]
Yup, looks okay...

**Pull request merged**
