### PR TITLE
Adding quotations to one of the params variable.

### PR DESCRIPTION
**Pull request by amanda-tarafa**
Fixes the Kokoro failures that we had over the weekend.

### CODE REVIEW

**Comment by amanda-tarafa** [comment]
@iantalarico for some reason I still can't merge this PR with your approval.
I'll have to wait for @jskeet's approval.

**Comment by iantalarico** [comment]
@amanda-tarafa Yea I saw that too.  I wonder if the permissions changed when we moved to 'googleapis'?  

@jskeet Can you check the permissions on the repo?

**Comment by jskeet** [comment]
Merging without a review is blocked for non-admins - that's by design from the DPE team. We can look at getting that changed if necessary. I believe the review can be any contributor though.

(Reviewing now)

**Comment by iantalarico** [comment]
@jskeet I'm okay with that (I have this set on our other repos) just surprised we aren't admins of the repo?

**Comment by amanda-tarafa** [comment]
Thanks!

**Pull request merged**
