### PR TITLE
Migrate TextToSpeech to the microgenerator

### PR DESCRIPTION
**Pull request by jskeet**
This is an FYI at the moment.

### CODE REVIEW

**Comment by chrisdunelm** [comment]
Looking good so far.
I haven't yet looked in enough detail to be sure what the changes in test and snippets are really about.

**Comment by jskeet** [comment]
Ooh, that's a mistake, I believe - and one that would impact documentation. Could you change the generator for that? (I'll regenerate to then include the builder, too.)

**Comment by chrisdunelm** [comment]
Yes, I'll change it now

**Comment by jskeet** [comment]
This now works, including snippets and smoke tests. Ready to merge on green.

**Pull request merged**
