### PR TITLE
Release Google.Cloud.Compute.V1 version 1.0.0-alpha01

### PR DESCRIPTION
**Pull request by jskeet**
Changes in this release:

First alpha release. Please note that this library is still in early testing phases, and is not suitable for production workloads.

### CODE REVIEW

**Comment by jskeet** [comment]
Note: we'll want to merge #6462 first.

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Comment by jskeet** [comment]
Thanks - will just get the all clear from the REGAPIC team before merging.

**Review by vchudnov-g — APPROVED** [review]
I think we're good to release. Thank you!

**Pull request merged**
