### PR TITLE
Regenerate APIs

### PR DESCRIPTION
**Pull request by jskeet**

### CODE REVIEW

**Comment by amanda-tarafa** [comment]
The last commit didn't passed Travis.

**Comment by jskeet** [comment]
It's actually the first commit that's broken, because of the use of an obsolete property. I think we'll need to modify either the project files or the test generator for that.

**Comment by jskeet** [comment]
Oh, and the smoke test has been broken :(

**Comment by jskeet** [comment]
It looks like the Container config needs significant work. I'll rebase without that commit.

**Comment by jskeet** [comment]
I've done a quick double-check, and it's all just additions. (All of this was autogenerated, of course.)

Happy to walk you through the codegen process at some point :)

**Pull request merged**
