### PR TITLE
Regenerate all APIs

### PR DESCRIPTION
**Pull request by jskeet**
First just regenerate Vision with the "old" generator to get a clean change later, then regenerate everything with the newest generator to get string overloads for resource names.

### CODE REVIEW

**Comment by jskeet** [comment]
I'll look into the logging failure.

**Comment by chrisdunelm** [comment]
A quick thought: for a change containing this much code (albeit auto-generated), might it be worth getting it all running through the [version compatibility detector](https://github.com/googleapis/google-cloud-dotnet/tree/master/tools/Google.Cloud.Tools.VersionCompat) to increase our confidence in this PRs correctness?

**Comment by jskeet** [comment]
Good idea. Will have a look at doing that tomorrow.

**Comment by jskeet** [comment]
Have just run the compatibility tester on all DLLs, and all are either identical or minor. Merging now, and will create a new PR with the script that does all that :)

**Comment by chrisdunelm** [comment]
Excellent :)

**Pull request merged**
