### PR TITLE
Add Google.Cloud.Optimization.V1 API

### PR DESCRIPTION
**Pull request by jskeet**
No smoke tests as there's nothing suitable; no release as it's not generally available yet.

### CODE REVIEW

**Comment by jskeet** [comment]
The snippet-bot-check is failing for this reason:

Some region tags do not have appropriate prefix
There are 4 possible violations for not having product prefix.

- [apis/Google.Cloud.Optimization.V1/Google.Cloud.Optimiza- tion.V1.GeneratedSnippets/FleetRoutingClient.BatchOptimizeToursRequestObjectAsyncSnippet.g.cs:19](https://github.com/jskeet/google-cloud-dotnet/blob/915737b8cc864fb9a951149e563c7602f6d2cf30/apis/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1.GeneratedSnippets/FleetRoutingClient.BatchOptimizeToursRequestObjectAsyncSnippet.g.cs#L19), tag cloudoptimization_v1_generated_FleetRouting_BatchOptimizeTours_async
- [apis/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1.GeneratedSnippets/FleetRoutingClient.BatchOptimizeToursRequestObjectSnippet.g.cs:19](https://github.com/jskeet/google-cloud-dotnet/blob/915737b8cc864fb9a951149e563c7602f6d2cf30/apis/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1.GeneratedSnippets/FleetRoutingClient.BatchOptimizeToursRequestObjectSnippet.g.cs#L19), tag cloudoptimization_v1_generated_FleetRouting_BatchOptimizeTours_sync
- [apis/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1.GeneratedSnippets/FleetRoutingClient.OptimizeToursRequestObjectAsyncSnippet.g.cs:19](https://github.com/jskeet/google-cloud-dotnet/blob/915737b8cc864fb9a951149e563c7602f6d2cf30/apis/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1.GeneratedSnippets/FleetRoutingClient.OptimizeToursRequestObjectAsyncSnippet.g.cs#L19), tag cloudoptimization_v1_generated_FleetRouting_OptimizeTours_async
- [apis/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1.GeneratedSnippets/FleetRoutingClient.OptimizeToursRequestObjectSnippet.g.cs:19](https://github.com/jskeet/google-cloud-dotnet/blob/915737b8cc864fb9a951149e563c7602f6d2cf30/apis/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1.GeneratedSnippets/FleetRoutingClient.OptimizeToursRequestObjectSnippet.g.cs#L19), tag cloudoptimization_v1_generated_FleetRouting_OptimizeTours_sync

Amanda, any idea what this means?

**Comment by amanda-tarafa** [comment]
Fixing the SnippetBot error. This is expected for some products. I'll add the `snippet-bot: no-prefix-req` label.

**Comment by jskeet** [comment]
Reopened to try to retrigger the snippet bot check.

**Comment by jskeet** [comment]
Hmm... snippet check is still failing. Amanda, let me know how you want us to handle this PR.

**Comment by jskeet** [comment]
(I think we may just have a GitHub actions backlog and it was taking a while to re-run.)

**Comment by amanda-tarafa** [comment]
Yep, I was checking from time to time and the bot hadn't rerun.

**Pull request merged**
