### PR TITLE
Configurable replication topology support

### PR DESCRIPTION
**Pull request by AlexandrTrf**

### CODE REVIEW

**Comment by jskeet** [comment]
Please email me internally (although I won't be reading work email again until tomorrow UK time). More context is required, including why we're not just waiting for the normal OwlBot publication process.

**Comment by jskeet** [comment]
I *believe* there's no expectation that the generated code should be created as a pull request, instead just used for local development. I'm requesting clarification on this though.

(If we were to merge this, then any other change to the public protos would end up regenerating and overwriting these changes - or worse, overwriting *some* of these changes, but not all.)

**Comment by rahul2393** [comment]
@AlexandrTrf thanks for working on this, all the generated code is supposed to be merged by automated process so no need to open the PR for it, but keep the feature branch active in your forked repo, for samples please create the PR in samples repo [here](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/), 4 new samples will be added and related smoking tests you can take reference from these.
https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1589/
https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/960

Let me know if you have any queries, thanks

**Comment by jskeet** [comment]
Thanks @rahul2393. Closing this PR (but leaving the branch where it is).

**Pull request closed without merging**
