### PR TITLE
feat: Copies generated standalone snippets

### PR DESCRIPTION
**Pull request by amanda-tarafa**
This is ready for review.

But we can merge when we are ready, probably after we have all snippet metadata generation ready.

### CODE REVIEW

**Review by jskeet — APPROVED** [review]
Presumably the plan is to merge this, then rerun the project file generator to regenerate the OwlBot configs? (A one-time generateapis.sh will pull in the standalone snippets, too.) All looks fine as shown though.

**Comment by amanda-tarafa** [comment]
> Presumably the plan is to merge this, then rerun the project file generator to regenerate the OwlBot configs? (A one-time generateapis.sh will pull in the standalone snippets, too.) All looks fine as shown though.

Yes, I was planning on that exactly. Maybe even add one last commit to this PR with the result of generateapis.sh, but I won't do that until we are ready as that commit may become stale quickly.

**Comment by amanda-tarafa** [comment]
@jskeet third commit is including all generated standalone snippets if you want to take a look.
There seems to be a bug on namespace disambiguation, I'll take a look at it in the generator.

**Comment by jskeet** [comment]
It's hard to see the actual diffs, but one thing I noted is that we've got coverage.xml in the StandaloneSnippets. Given that there aren't any actual tests, we probably shouldn't have coverage.xml

**Comment by amanda-tarafa** [comment]
I'll look at not generating the coverage.xml file as well.

**Comment by amanda-tarafa** [comment]
This is ready to review as well. The last commit is the result of generating with these changes and the ones in googleapis/gapic-generator-csharp#417

**Review by jskeet — APPROVED** [review]
I can't actually review the third commit - even just trying to restrict it to non-.cs files causes issues on the review page. But if it all builds, that's fine.

**Comment by amanda-tarafa** [comment]
I'm dropping the last commit (regeneration) temporarily to make this PR manageable.
And we'll still need a fresh generation before merging, so we would have to drop it anyway.

**Comment by amanda-tarafa** [comment]
TODO before merging:

- Rebase making sure #7687 is in, and address conflicts.
- Make appropiate modifications on this PR to take into account the rename StandaloneSnippets -> GeneratedSnippets.

**Comment by amanda-tarafa** [comment]
Jon this is ready for review. The first two commits haven't changed since you approved. The third one is just regeneration, it's big though. I checked locally with a grep and everything seems to be as expected.

**Review by jskeet — APPROVED** [review]
Still LGTM - looking forward to when we've finished all the shuffling around and it's all in a beautiful state :)

**Pull request merged**
