### PR TITLE
PubSub: Avoid unobserved InvalidOperationException in AsyncSingleRecvQueue

### PR DESCRIPTION
**Pull request by lkts**
Fixes https://github.com/googleapis/google-cloud-dotnet/issues/2763.

This fixes unobserved exception which happened when `SetResult` was called multiple times.

~~Comment in code mentioned that problem was that continuations of `TaskCompletionSource` can run synchonously so i changed just that (i may be missing some details why it won't work). Also it is generally [recommended](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#always-create-taskcompletionsourcet-with-taskcreationoptionsruncontinuationsasynchronously) to use `TaskCreationOptions.RunContinuationsAsynchronously`.~~ - this does not build

Another approach it to use [TrySetResult](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcompletionsource-1.trysetresult?view=netcore-1.0) with current approach.

### CODE REVIEW

**Comment by jskeet** [comment]
I'll assign this to Chris as he's responsible for the PubSub code. He's on vacation until Monday, but I'm sure he'll look at it then.

**Comment by lkts** [comment]
@chrisdunelm @jskeet can you describe what your release approach is? When can we expect this fix to be released?

**Comment by jskeet** [comment]
@lkts: It depends on exactly what the situation is. In this case I'll let Chris think about it - I'd suggest we could probably do a 1.1.0-beta01 release fairly soon, as that doesn't stop us from adding more features for a 1.1.0 GA.

**Comment by lkts** [comment]
cool, thanks

**Comment by chrisdunelm** [comment]
1.1.0-beta01 is now released with this fix (and an updated gRPC dependency).

**Pull request merged**
